development:
  adapter: mysql2
  host: mysql
  database: wifi_comm_dev
  username: dbuser
  password: dbpass
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  host: mysql
  database: wifi_comm_dev
  username: dbuser
  password: dbpass
  reconnect: true
  pool: 5

test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
